export const data = [
    {
        "Users": "user1@gmail.com",
        "FinalRating": "Normal, Very low, Very low, Very low, Very low, Very low, Very low, Very low, Very low, Very low, Very low, Very low, Very low, Very low, Very low, Very low",
        "TotalTime": "0 : 1 : 22",
        "Problem 1 Iteration 1": [{"Decisions": "1-1-0"}, {"Rating": "High, Very low, Very low, Very low, Very low, Very low, Very low, Very low, Very low"}, {"Email Response": "In your opinion, what are the main areas where we could enhance our performance or efficiency? Do you have any specific recommendations or suggestions for improvement?\nAre there any emerging trends or technologies that you believe could positively impact our department? If yes, please provide details and your thoughts on their potential implementation.\nI kindly request that you provide your responses to these questions via email. I wish you continued success and look forward to receiving your valuable responses.\nRegards,"}, {"Iteration Start Time": "Fri Nov 03 2023 12:30:13 GMT+0500 (Pakistan Standard Time)"}, {"Iteration End Time": "Fri Nov 03 2023 12:31:03 GMT+0500 (Pakistan Standard Time)"}],
        "Problem 1 Iteration 2": [{"Decisions": "1-2-0"}, {"Rating": "High, Very low, Very low, Very low, Very low, Very low, Very low, Very low, Very low"}, {"Email Response": "In your opinion, what are the main areas where we could enhance our performance or efficiency? Do you have any specific recommendations or suggestions for improvement?\nAre there any emerging trends or technologies that you believe could positively impact our department? If yes, please provide details and your thoughts on their potential implementation.\nI kindly request that you provide your responses to these questions via email. I wish you continued success and look forward to receiving your valuable responses.\nRegards,"}, {"Iteration Start Time": "Fri Nov 03 2023 12:30:13 GMT+0500 (Pakistan Standard Time)"}, {"Iteration End Time": "Fri Nov 03 2023 12:31:03 GMT+0500 (Pakistan Standard Time)"}],
        "Problem 2 Iteration 1": [{"Decisions": "2-1-1"}, {"Rating": "High, Very low, Very low, Very low, Very low, Very low, Very low, Very low, Very low"}, {"Email Response": "In your opinion, what are the main areas where we could enhance our performance or efficiency? Do you have any specific recommendations or suggestions for improvement?\nAre there any emerging trends or technologies that you believe could positively impact our department? If yes, please provide details and your thoughts on their potential implementation.\nI kindly request that you provide your responses to these questions via email. I wish you continued success and look forward to receiving your valuable responses.\nRegards,"}, {"Iteration Start Time": "Fri Nov 03 2023 12:30:13 GMT+0500 (Pakistan Standard Time)"}, {"Iteration End Time": "Fri Nov 03 2023 12:31:03 GMT+0500 (Pakistan Standard Time)"}],
        "Problem 2 Iteration 2": [{"Decisions": "2-2-0"}, {"Rating": "High, Very low, Very low, Very low, Very low, Very low, Very low, Very low, Very low"}, {"Email Response": "In your opinion, what are the main areas where we could enhance our performance or efficiency? Do you have any specific recommendations or suggestions for improvement?\nAre there any emerging trends or technologies that you believe could positively impact our department? If yes, please provide details and your thoughts on their potential implementation.\nI kindly request that you provide your responses to these questions via email. I wish you continued success and look forward to receiving your valuable responses.\nRegards,"}, {"Iteration Start Time": "Fri Nov 03 2023 12:30:13 GMT+0500 (Pakistan Standard Time)"}, {"Iteration End Time": "Fri Nov 03 2023 12:31:03 GMT+0500 (Pakistan Standard Time)"}],
        "Problem 3 Iteration 1": [{"Decisions": "1-1-0"}, {"Rating": "High, Very low, Very low, Very low, Very low, Very low, Very low, Very low, Very low"}, {"Email Response": "In your opinion, what are the main areas where we could enhance our performance or efficiency? Do you have any specific recommendations or suggestions for improvement?\nAre there any emerging trends or technologies that you believe could positively impact our department? If yes, please provide details and your thoughts on their potential implementation.\nI kindly request that you provide your responses to these questions via email. I wish you continued success and look forward to receiving your valuable responses.\nRegards,"}, {"Iteration Start Time": "Fri Nov 03 2023 12:30:13 GMT+0500 (Pakistan Standard Time)"}, {"Iteration End Time": "Fri Nov 03 2023 12:31:03 GMT+0500 (Pakistan Standard Time)"}],
        "Problem 3 Iteration 2": [{"Decisions": "1-1-0"}, {"Rating": "High, Very low, Very low, Very low, Very low, Very low, Very low, Very low, Very low"}, {"Email Response": "In your opinion, what are the main areas where we could enhance our performance or efficiency? Do you have any specific recommendations or suggestions for improvement?\nAre there any emerging trends or technologies that you believe could positively impact our department? If yes, please provide details and your thoughts on their potential implementation.\nI kindly request that you provide your responses to these questions via email. I wish you continued success and look forward to receiving your valuable responses.\nRegards,"}, {"Iteration Start Time": "Fri Nov 03 2023 12:30:13 GMT+0500 (Pakistan Standard Time)"}, {"Iteration End Time": "Fri Nov 03 2023 12:31:03 GMT+0500 (Pakistan Standard Time)"}],
        "Problem 4 Iteration 1": [{"Decisions": "1-1-0"}, {"Rating": "High, Very low, Very low, Very low, Very low, Very low, Very low, Very low, Very low"}, {"Email Response": "In your opinion, what are the main areas where we could enhance our performance or efficiency? Do you have any specific recommendations or suggestions for improvement?\nAre there any emerging trends or technologies that you believe could positively impact our department? If yes, please provide details and your thoughts on their potential implementation.\nI kindly request that you provide your responses to these questions via email. I wish you continued success and look forward to receiving your valuable responses.\nRegards,"}, {"Iteration Start Time": "Fri Nov 03 2023 12:30:13 GMT+0500 (Pakistan Standard Time)"}, {"Iteration End Time": "Fri Nov 03 2023 12:31:03 GMT+0500 (Pakistan Standard Time)"}],
        "Problem 4 Iteration 2": [{"Decisions": "1-1-0"}, {"Rating": "High, Very low, Very low, Very low, Very low, Very low, Very low, Very low, Very low"}, {"Email Response": "In your opinion, what are the main areas where we could enhance our performance or efficiency? Do you have any specific recommendations or suggestions for improvement?\nAre there any emerging trends or technologies that you believe could positively impact our department? If yes, please provide details and your thoughts on their potential implementation.\nI kindly request that you provide your responses to these questions via email. I wish you continued success and look forward to receiving your valuable responses.\nRegards,"}, {"Iteration Start Time": "Fri Nov 03 2023 12:30:13 GMT+0500 (Pakistan Standard Time)"}, {"Iteration End Time": "Fri Nov 03 2023 12:31:03 GMT+0500 (Pakistan Standard Time)"}],
        "Problem 5 Iteration 1": [{"Decisions": "1-1-0"}, {"Rating": "High, Very low, Very low, Very low, Very low, Very low, Very low, Very low, Very low"}, {"Email Response": "In your opinion, what are the main areas where we could enhance our performance or efficiency? Do you have any specific recommendations or suggestions for improvement?\nAre there any emerging trends or technologies that you believe could positively impact our department? If yes, please provide details and your thoughts on their potential implementation.\nI kindly request that you provide your responses to these questions via email. I wish you continued success and look forward to receiving your valuable responses.\nRegards,"}, {"Iteration Start Time": "Fri Nov 03 2023 12:30:13 GMT+0500 (Pakistan Standard Time)"}, {"Iteration End Time": "Fri Nov 03 2023 12:31:03 GMT+0500 (Pakistan Standard Time)"}],
        "Problem 5 Iteration 2": [{"Decisions": "1-1-0"}, {"Rating": "High, Very low, Very low, Very low, Very low, Very low, Very low, Very low, Very low"}, {"Email Response": "In your opinion, what are the main areas where we could enhance our performance or efficiency? Do you have any specific recommendations or suggestions for improvement?\nAre there any emerging trends or technologies that you believe could positively impact our department? If yes, please provide details and your thoughts on their potential implementation.\nI kindly request that you provide your responses to these questions via email. I wish you continued success and look forward to receiving your valuable responses.\nRegards,"}, {"Iteration Start Time": "Fri Nov 03 2023 12:30:13 GMT+0500 (Pakistan Standard Time)"}, {"Iteration End Time": "Fri Nov 03 2023 12:31:03 GMT+0500 (Pakistan Standard Time)"}],
            
    },
    {
        "Users": "user2@gmail.com",
        "Problem 1 Iteration 1": [{"Decisions": "1-1-0"}, {"Rating": "High, Very low, Very low, Very low, Very low, Very low, Very low, Very low, Very low"}, {"Email Response": "In your opinion, what are the main areas where we could enhance our performance or efficiency? Do you have any specific recommendations or suggestions for improvement?\nAre there any emerging trends or technologies that you believe could positively impact our department? If yes, please provide details and your thoughts on their potential implementation.\nI kindly request that you provide your responses to these questions via email. I wish you continued success and look forward to receiving your valuable responses.\nRegards,"}, {"Iteration Start Time": "Fri Nov 03 2023 12:30:13 GMT+0500 (Pakistan Standard Time)"}, {"Iteration End Time": "Fri Nov 03 2023 12:31:03 GMT+0500 (Pakistan Standard Time)"}],
        "Problem 1 Iteration 2": [{"Decisions": "1-1-0"}, {"Rating": "High, Very low, Very low, Very low, Very low, Very low, Very low, Very low, Very low"}, {"Email Response": "In your opinion, what are the main areas where we could enhance our performance or efficiency? Do you have any specific recommendations or suggestions for improvement?\nAre there any emerging trends or technologies that you believe could positively impact our department? If yes, please provide details and your thoughts on their potential implementation.\nI kindly request that you provide your responses to these questions via email. I wish you continued success and look forward to receiving your valuable responses.\nRegards,"}, {"Iteration Start Time": "Fri Nov 03 2023 12:30:13 GMT+0500 (Pakistan Standard Time)"}, {"Iteration End Time": "Fri Nov 03 2023 12:31:03 GMT+0500 (Pakistan Standard Time)"}],
    },
    {
        "Users": "user3@gmail.com"
    }
]