export const tempData = [
    [
        {
            "user1@gmail.com": [
                {
                    "decisions": "7-2-0",
                    "Problem": 7,
                    "Iteration": 2,
                    "rating": [
                        "Very high",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 16:48:25 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 16:48:37 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "Normal",
                        "High",
                        "Normal",
                        "High",
                        "Very low",
                        "Very high",
                        "Very low",
                        "Very low",
                        "Normal",
                        "Very high",
                        "Low",
                        "Very high",
                        "Normal",
                        "Low",
                        "High",
                        "Low"
                    ],
                    "totalTime": "00: 03 : 25"
                },
                {
                    "decisions": "3-2-0",
                    "Problem": 3,
                    "Iteration": 2,
                    "rating": [
                        "Very high",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 16:48:53 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 16:49:07 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "Normal",
                        "High",
                        "Normal",
                        "High",
                        "Very low",
                        "Very high",
                        "Very low",
                        "Very low",
                        "Normal",
                        "Very high",
                        "Low",
                        "Very high",
                        "Normal",
                        "Low",
                        "High",
                        "Low"
                    ],
                    "totalTime": "00: 03 : 25"
                },
                {
                    "decisions": "6-2-1",
                    "Problem": 6,
                    "Iteration": 2,
                    "rating": [
                        "Normal",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 16:47:37 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 16:48:03 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "Normal",
                        "High",
                        "Normal",
                        "High",
                        "Very low",
                        "Very high",
                        "Very low",
                        "Very low",
                        "Normal",
                        "Very high",
                        "Low",
                        "Very high",
                        "Normal",
                        "Low",
                        "High",
                        "Low"
                    ],
                    "totalTime": "00: 03 : 25",
                    "emailResponse": "Given your key role in [specific department or project], I would greatly appreciate it if you could take some time to answer a few questions via email. Your responses will enable us to gain a better understanding of the current state of affairs and identify potential areas for improvement.\n\nI understand that your time is valuable, and I want to assure you that your contribution will be highly valued and directly impact the future direction of our organization. Your honest and constructive feedback will help us make informed decisions and take necessary actions to drive positive change. Without further ado, here are the questions. I kindly request you to address:"
                },
                {
                    "decisions": "1-1-0",
                    "Problem": 1,
                    "Iteration": 1,
                    "rating": [
                        "Normal",
                        "Very low",
                        "Normal",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 16:44:07 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 16:44:47 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "Normal",
                        "High",
                        "Normal",
                        "High",
                        "Very low",
                        "Very high",
                        "Very low",
                        "Very low",
                        "Normal",
                        "Very high",
                        "Low",
                        "Very high",
                        "Normal",
                        "Low",
                        "High",
                        "Low"
                    ],
                    "totalTime": "00: 03 : 25",
                    "emailResponse": "will enable us to gain a better understanding of the current state of affairs and identify potential areas for improvement.\n\nI understand that your time is valuable, and I want to assure you that your contribution will be highly valued and directly impact the future direction of our organization. Your honest and constructive feedback will help us make informed decisions and take necessary actions to drive positive change. Without further ado, here are the questions. I kindly request you to address:"
                },
                {
                    "decisions": "4-1-0",
                    "Problem": 4,
                    "Iteration": 1,
                    "rating": [
                        "Normal",
                        "Very low",
                        "Very low",
                        "Normal",
                        "Very low",
                        "Low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 16:45:38 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 16:46:03 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "Normal",
                        "High",
                        "Normal",
                        "High",
                        "Very low",
                        "Very high",
                        "Very low",
                        "Very low",
                        "Normal",
                        "Very high",
                        "Low",
                        "Very high",
                        "Normal",
                        "Low",
                        "High",
                        "Low"
                    ],
                    "totalTime": "00: 03 : 25"
                },
                {
                    "decisions": "7-1-0",
                    "Problem": 7,
                    "Iteration": 1,
                    "rating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 16:48:03 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 16:48:25 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "Normal",
                        "High",
                        "Normal",
                        "High",
                        "Very low",
                        "Very high",
                        "Very low",
                        "Very low",
                        "Normal",
                        "Very high",
                        "Low",
                        "Very high",
                        "Normal",
                        "Low",
                        "High",
                        "Low"
                    ],
                    "totalTime": "00: 03 : 25"
                },
                {
                    "decisions": "1-2-0",
                    "Problem": 1,
                    "Iteration": 2,
                    "rating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 16:46:51 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 16:47:10 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "Normal",
                        "High",
                        "Normal",
                        "High",
                        "Very low",
                        "Very high",
                        "Very low",
                        "Very low",
                        "Normal",
                        "Very high",
                        "Low",
                        "Very high",
                        "Normal",
                        "Low",
                        "High",
                        "Low"
                    ],
                    "totalTime": "00: 03 : 25"
                },
                {
                    "decisions": "8-2-0",
                    "Problem": 8,
                    "Iteration": 2,
                    "rating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 16:48:37 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 16:48:53 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "Normal",
                        "High",
                        "Normal",
                        "High",
                        "Very low",
                        "Very high",
                        "Very low",
                        "Very low",
                        "Normal",
                        "Very high",
                        "Low",
                        "Very high",
                        "Normal",
                        "Low",
                        "High",
                        "Low"
                    ],
                    "totalTime": "00: 03 : 25"
                },
                {
                    "decisions": "8-1-0",
                    "Problem": 8,
                    "Iteration": 1,
                    "rating": [
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 16:48:03 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 16:48:25 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "Normal",
                        "High",
                        "Normal",
                        "High",
                        "Very low",
                        "Very high",
                        "Very low",
                        "Very low",
                        "Normal",
                        "Very high",
                        "Low",
                        "Very high",
                        "Normal",
                        "Low",
                        "High",
                        "Low"
                    ],
                    "totalTime": "00: 03 : 25"
                },
                {
                    "decisions": "6-1-1",
                    "Problem": 6,
                    "Iteration": 1,
                    "rating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 16:47:24 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 16:47:37 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "Normal",
                        "High",
                        "Normal",
                        "High",
                        "Very low",
                        "Very high",
                        "Very low",
                        "Very low",
                        "Normal",
                        "Very high",
                        "Low",
                        "Very high",
                        "Normal",
                        "Low",
                        "High",
                        "Low"
                    ],
                    "totalTime": "00: 03 : 25"
                },
                {
                    "decisions": "5-2-0",
                    "Problem": 5,
                    "Iteration": 2,
                    "rating": [
                        "Normal",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 16:46:20 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 16:46:51 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "Normal",
                        "High",
                        "Normal",
                        "High",
                        "Very low",
                        "Very high",
                        "Very low",
                        "Very low",
                        "Normal",
                        "Very high",
                        "Low",
                        "Very high",
                        "Normal",
                        "Low",
                        "High",
                        "Low"
                    ],
                    "totalTime": "00: 03 : 25"
                },
                {
                    "decisions": "1-1-0",
                    "Problem": 1,
                    "Iteration": 1,
                    "rating": [
                        "Normal",
                        "Very low",
                        "Normal",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 16:44:07 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 16:44:47 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "Normal",
                        "High",
                        "Normal",
                        "High",
                        "Very low",
                        "Very high",
                        "Very low",
                        "Very low",
                        "Normal",
                        "Very high",
                        "Low",
                        "Very high",
                        "Normal",
                        "Low",
                        "High",
                        "Low"
                    ],
                    "totalTime": "00: 03 : 25",
                    "emailResponse": "will enable us to gain a better understanding of the current state of affairs and identify potential areas for improvement.\n\nI understand that your time is valuable, and I want to assure you that your contribution will be highly valued and directly impact the future direction of our organization. Your honest and constructive feedback will help us make informed decisions and take necessary actions to drive positive change. Without further ado, here are the questions. I kindly request you to address:"
                },
                {
                    "decisions": "5-1-1",
                    "Problem": 5,
                    "Iteration": 1,
                    "rating": [
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 16:45:38 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 16:46:03 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "Normal",
                        "High",
                        "Normal",
                        "High",
                        "Very low",
                        "Very high",
                        "Very low",
                        "Very low",
                        "Normal",
                        "Very high",
                        "Low",
                        "Very high",
                        "Normal",
                        "Low",
                        "High",
                        "Low"
                    ],
                    "totalTime": "00: 03 : 25"
                },
                {
                    "decisions": "4-2-0",
                    "Problem": 4,
                    "Iteration": 2,
                    "rating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 16:46:03 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 16:46:20 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "Normal",
                        "High",
                        "Normal",
                        "High",
                        "Very low",
                        "Very high",
                        "Very low",
                        "Very low",
                        "Normal",
                        "Very high",
                        "Low",
                        "Very high",
                        "Normal",
                        "Low",
                        "High",
                        "Low"
                    ],
                    "totalTime": "00: 03 : 25"
                },
                {
                    "decisions": "3-1-2",
                    "Problem": 3,
                    "Iteration": 1,
                    "rating": [
                        "Normal",
                        "Very low",
                        "Normal",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 16:45:02 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 16:45:38 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "Normal",
                        "High",
                        "Normal",
                        "High",
                        "Very low",
                        "Very high",
                        "Very low",
                        "Very low",
                        "Normal",
                        "Very high",
                        "Low",
                        "Very high",
                        "Normal",
                        "Low",
                        "High",
                        "Low"
                    ],
                    "totalTime": "00: 03 : 25",
                    "emailResponse": "I understand that your time is valuable, and I want to assure you that your contribution will be highly valued and directly impact the future direction of our organization. Your honest and constructive feedback will help us make informed decisions and take necessary actions to drive positive change. Without further ado, here are the questions. I kindly request you to address:"
                },
                {
                    "decisions": "2-1-0",
                    "Problem": 2,
                    "Iteration": 1,
                    "rating": [
                        "Normal",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 16:44:47 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 16:45:02 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "Normal",
                        "High",
                        "Normal",
                        "High",
                        "Very low",
                        "Very high",
                        "Very low",
                        "Very low",
                        "Normal",
                        "Very high",
                        "Low",
                        "Very high",
                        "Normal",
                        "Low",
                        "High",
                        "Low"
                    ],
                    "totalTime": "00: 03 : 25"
                },
                {
                    "decisions": "2-2-1",
                    "Problem": 2,
                    "Iteration": 2,
                    "rating": [
                        "Normal",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 16:47:10 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 16:47:24 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "Normal",
                        "High",
                        "Normal",
                        "High",
                        "Very low",
                        "Very high",
                        "Very low",
                        "Very low",
                        "Normal",
                        "Very high",
                        "Low",
                        "Very high",
                        "Normal",
                        "Low",
                        "High",
                        "Low"
                    ],
                    "totalTime": "00: 03 : 25"
                }
            ]
        },
        {
            "user2@gmail.com": [
                {
                    "decisions": "7-2-1",
                    "Problem": 7,
                    "Iteration": 2,
                    "rating": [
                        "Very high",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Tue Nov 14 2023 13:36:39 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Tue Nov 14 2023 13:36:53 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "5-1-0",
                    "Problem": 5,
                    "Iteration": 1,
                    "rating": [
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 17:08:25 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 17:08:50 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "5-2-0",
                    "Problem": 5,
                    "Iteration": 2,
                    "rating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Normal",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 17:18:53 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 17:36:40 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "2-2-0",
                    "Problem": 2,
                    "Iteration": 2,
                    "rating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 17:02:43 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 17:02:57 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "4-2-0",
                    "Problem": 4,
                    "Iteration": 2,
                    "rating": [
                        "Very high",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 17:08:50 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 17:09:04 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "6-1-0",
                    "Problem": 6,
                    "Iteration": 1,
                    "rating": [
                        "Normal",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Tue Nov 14 2023 13:35:11 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Tue Nov 14 2023 13:35:24 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "2-2-0",
                    "Problem": 2,
                    "Iteration": 2,
                    "rating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 17:02:43 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 17:02:57 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "3-2-0",
                    "Problem": 3,
                    "Iteration": 2,
                    "rating": [
                        "High",
                        "Very low",
                        "Low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 17:05:47 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 17:06:06 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "6-2-0",
                    "Problem": 6,
                    "Iteration": 2,
                    "rating": [
                        "Very high",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Tue Nov 14 2023 13:35:24 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Tue Nov 14 2023 13:35:37 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "8-1-0",
                    "Problem": 8,
                    "Iteration": 1,
                    "rating": [
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Tue Nov 14 2023 13:35:37 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Tue Nov 14 2023 13:35:58 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "7-1-0",
                    "Problem": 7,
                    "Iteration": 1,
                    "rating": [
                        "Normal",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Tue Nov 14 2023 13:35:37 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Tue Nov 14 2023 13:35:58 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "3-1-0",
                    "Problem": 3,
                    "Iteration": 1,
                    "rating": [
                        "Very high",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Tue Nov 14 2023 13:34:12 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Tue Nov 14 2023 13:34:24 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "3-2-0",
                    "Problem": 3,
                    "Iteration": 2,
                    "rating": [
                        "High",
                        "Very low",
                        "Low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 17:05:47 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 17:06:06 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "4-1-0",
                    "Problem": 4,
                    "Iteration": 1,
                    "rating": [
                        "Normal",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 17:08:25 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 17:08:50 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "1-2-1",
                    "Problem": 1,
                    "Iteration": 2,
                    "rating": [
                        "High",
                        "High",
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 17:06:19 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 17:06:36 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "8-2-0",
                    "Problem": 8,
                    "Iteration": 2,
                    "rating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Tue Nov 14 2023 13:35:58 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Tue Nov 14 2023 13:36:10 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "1-1-0",
                    "Problem": 1,
                    "Iteration": 1,
                    "rating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 16:49:51 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 16:50:07 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13",
                    "emailResponse": "Given your key role in [specific department or project], I would greatly appreciate it if you could take some time to answer a few questions via email. Your responses will enable us to gain a better understanding of the current state of affairs and identify potential areas for improvement.\n\nI understand that your time is valuable, and I want to assure you that your contribution will be highly valued and directly impact the future direction of our organization. Your honest and constructive feedback will help us make informed decisions and take necessary actions to drive positive change. Without further ado, here are the questions. I kindly request you to address:"
                },
                {
                    "decisions": "1-1-0",
                    "Problem": 1,
                    "Iteration": 1,
                    "rating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 16:49:51 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 16:50:07 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13",
                    "emailResponse": "Given your key role in [specific department or project], I would greatly appreciate it if you could take some time to answer a few questions via email. Your responses will enable us to gain a better understanding of the current state of affairs and identify potential areas for improvement.\n\nI understand that your time is valuable, and I want to assure you that your contribution will be highly valued and directly impact the future direction of our organization. Your honest and constructive feedback will help us make informed decisions and take necessary actions to drive positive change. Without further ado, here are the questions. I kindly request you to address:"
                },
                {
                    "decisions": "5-2-0",
                    "Problem": 5,
                    "Iteration": 2,
                    "rating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Normal",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 17:18:53 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 17:36:40 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "2-1-0",
                    "Problem": 2,
                    "Iteration": 1,
                    "rating": [
                        "Very high",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Tue Nov 14 2023 13:34:00 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Tue Nov 14 2023 13:34:12 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "3-1-0",
                    "Problem": 3,
                    "Iteration": 1,
                    "rating": [
                        "Very high",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Tue Nov 14 2023 13:34:12 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Tue Nov 14 2023 13:34:24 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "4-1-0",
                    "Problem": 4,
                    "Iteration": 1,
                    "rating": [
                        "Normal",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 17:08:25 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 17:08:50 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "1-1-0",
                    "Problem": 1,
                    "Iteration": 1,
                    "rating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 16:49:51 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 16:50:07 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13",
                    "emailResponse": "Given your key role in [specific department or project], I would greatly appreciate it if you could take some time to answer a few questions via email. Your responses will enable us to gain a better understanding of the current state of affairs and identify potential areas for improvement.\n\nI understand that your time is valuable, and I want to assure you that your contribution will be highly valued and directly impact the future direction of our organization. Your honest and constructive feedback will help us make informed decisions and take necessary actions to drive positive change. Without further ado, here are the questions. I kindly request you to address:"
                },
                {
                    "decisions": "1-2-0",
                    "Problem": 1,
                    "Iteration": 2,
                    "rating": [
                        "High",
                        "High",
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 17:06:19 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 17:06:36 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "5-1-0",
                    "Problem": 5,
                    "Iteration": 1,
                    "rating": [
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 17:08:25 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 17:08:50 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "4-2-0",
                    "Problem": 4,
                    "Iteration": 2,
                    "rating": [
                        "Very high",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Fri Nov 10 2023 17:08:50 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Fri Nov 10 2023 17:09:04 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                },
                {
                    "decisions": "2-1-0, 2-1-1",
                    "Problem": 2,
                    "Iteration": 1,
                    "rating": [
                        "Very high",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Tue Nov 14 2023 13:34:00 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Tue Nov 14 2023 13:34:12 GMT+0500 (Pakistan Standard Time)",
                    "finalRating": [
                        "High",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "totalTime": "92 : 47 : 13"
                }
            ]
        },
    ],
    [
        {
            "user3@gmail.com": [
                {
                    "decisions": "1-2-0",
                    "Problem": 1,
                    "Iteration": 2,
                    "rating": [
                        "Normal",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Mon Nov 13 2023 19:31:51 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Mon Nov 13 2023 19:32:05 GMT+0500 (Pakistan Standard Time)"
                },
                {
                    "decisions": "1-1-0, 1-1-1",
                    "Problem": 1,
                    "Iteration": 1,
                    "rating": [
                        "Normal",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Mon Nov 13 2023 19:31:29 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Mon Nov 13 2023 19:31:51 GMT+0500 (Pakistan Standard Time)",
                    "emailResponse": "Given your key role in [specific department or project], I would greatly appreciate it if you could take some time to answer a few questions via email. Your responses will enable us to gain a better understanding of the current state of affairs and identify potential areas for improvement.\n\nI understand that your time is valuable, and I want to assure you that your contribution will be highly valued and directly impact the future direction of our organization. Your honest and constructive feedback will help us make informed decisions and take necessary actions to drive positive change. Without further ado, here are the questions. I kindly request you to address:"
                }
            ]
        },
    ],
    [
        {
            "user4@gmail.com": [
                {
                    "decisions": "1-1-0",
                    "Problem": 1,
                    "Iteration": 1,
                    "rating": [
                        "Normal",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low",
                        "Very low"
                    ],
                    "startTime": "Tue Nov 14 2023 12:28:42 GMT+0500 (Pakistan Standard Time)",
                    "endTime": "Tue Nov 14 2023 12:29:00 GMT+0500 (Pakistan Standard Time)",
                    "emailResponse": "Given your key role in [specific department or project], I would greatly appreciate it if you could take some time to answer a few questions via email. Your responses will enable us to gain a better understanding of the current state of affairs and identify potential areas for improvement.\n\nI understand that your time is valuable, and I want to assure you that your contribution will be highly valued and directly impact the future direction of our organization. Your honest and constructive feedback will help us make informed decisions and take necessary actions to drive positive change. Without further ado, here are the questions. I kindly request you to address:"
                }
            ]
        },
    ]
]